<?php

namespace AppBundle\Repository;

/**
 * ReservationEquipmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservationEquipmentRepository extends \Doctrine\ORM\EntityRepository
{
}
