<?php

namespace AppBundle\Repository;

/**
 * StaffRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StaffRepository extends \Doctrine\ORM\EntityRepository
{
}
