<?php

namespace AppBundle\Repository;

/**
 * StuffRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StuffRepository extends \Doctrine\ORM\EntityRepository
{
}
