<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'argument_resolver.service' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Controller/ArgumentValueResolverInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Controller/ArgumentResolver/ServiceValueResolver.php';

return $this->services['argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\ServiceLocator(array('AppBundle\\Controller\\EquipmentController:deleteAction' => function () {
    return ${($_ = isset($this->services['service_locator.vktf0xf']) ? $this->services['service_locator.vktf0xf'] : $this->load('getServiceLocator_Vktf0xfService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\EquipmentController:downOrderAction' => function () {
    return ${($_ = isset($this->services['service_locator.vktf0xf']) ? $this->services['service_locator.vktf0xf'] : $this->load('getServiceLocator_Vktf0xfService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\EquipmentController:upOrderAction' => function () {
    return ${($_ = isset($this->services['service_locator.vktf0xf']) ? $this->services['service_locator.vktf0xf'] : $this->load('getServiceLocator_Vktf0xfService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\ReservationController:deleteAction' => function () {
    return ${($_ = isset($this->services['service_locator.zqxutv5']) ? $this->services['service_locator.zqxutv5'] : $this->load('getServiceLocator_Zqxutv5Service.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\ReservationController:showAction' => function () {
    return ${($_ = isset($this->services['service_locator.zqxutv5']) ? $this->services['service_locator.zqxutv5'] : $this->load('getServiceLocator_Zqxutv5Service.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\StaffController:deleteAction' => function () {
    return ${($_ = isset($this->services['service_locator.p9g9b3n']) ? $this->services['service_locator.p9g9b3n'] : $this->load('getServiceLocator_P9g9b3nService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\StaffController:downOrderAction' => function () {
    return ${($_ = isset($this->services['service_locator.p9g9b3n']) ? $this->services['service_locator.p9g9b3n'] : $this->load('getServiceLocator_P9g9b3nService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\StaffController:upOrderAction' => function () {
    return ${($_ = isset($this->services['service_locator.p9g9b3n']) ? $this->services['service_locator.p9g9b3n'] : $this->load('getServiceLocator_P9g9b3nService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\EquipmentController::deleteAction' => function () {
    return ${($_ = isset($this->services['service_locator.vktf0xf']) ? $this->services['service_locator.vktf0xf'] : $this->load('getServiceLocator_Vktf0xfService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\EquipmentController::downOrderAction' => function () {
    return ${($_ = isset($this->services['service_locator.vktf0xf']) ? $this->services['service_locator.vktf0xf'] : $this->load('getServiceLocator_Vktf0xfService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\EquipmentController::upOrderAction' => function () {
    return ${($_ = isset($this->services['service_locator.vktf0xf']) ? $this->services['service_locator.vktf0xf'] : $this->load('getServiceLocator_Vktf0xfService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\ReservationController::deleteAction' => function () {
    return ${($_ = isset($this->services['service_locator.zqxutv5']) ? $this->services['service_locator.zqxutv5'] : $this->load('getServiceLocator_Zqxutv5Service.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\ReservationController::showAction' => function () {
    return ${($_ = isset($this->services['service_locator.zqxutv5']) ? $this->services['service_locator.zqxutv5'] : $this->load('getServiceLocator_Zqxutv5Service.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\StaffController::deleteAction' => function () {
    return ${($_ = isset($this->services['service_locator.p9g9b3n']) ? $this->services['service_locator.p9g9b3n'] : $this->load('getServiceLocator_P9g9b3nService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\StaffController::downOrderAction' => function () {
    return ${($_ = isset($this->services['service_locator.p9g9b3n']) ? $this->services['service_locator.p9g9b3n'] : $this->load('getServiceLocator_P9g9b3nService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\StaffController::upOrderAction' => function () {
    return ${($_ = isset($this->services['service_locator.p9g9b3n']) ? $this->services['service_locator.p9g9b3n'] : $this->load('getServiceLocator_P9g9b3nService.php')) && false ?: '_'};
})));
