<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'AppBundle\Service\OrderService' shared autowired service.

include_once $this->targetDirs[3].'/src/AppBundle/Service/OrderService.php';

return $this->services['AppBundle\Service\OrderService'] = new \AppBundle\Service\OrderService(${($_ = isset($this->services['doctrine.orm.default_entity_manager']) ? $this->services['doctrine.orm.default_entity_manager'] : $this->load('getDoctrine_Orm_DefaultEntityManagerService.php')) && false ?: '_'});
