<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.p9g9b3n' shared service.

return $this->services['service_locator.p9g9b3n'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('orderService' => function () {
    $f = function (\AppBundle\Service\OrderService $v = null) { return $v; }; return $f(${($_ = isset($this->services['AppBundle\Service\OrderService']) ? $this->services['AppBundle\Service\OrderService'] : $this->load('getOrderServiceService.php')) && false ?: '_'});
}));
