<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'AppBundle\Service\SignatureService' shared autowired service.

include_once $this->targetDirs[3].'/src/AppBundle/Service/SignatureService.php';

return $this->services['AppBundle\Service\SignatureService'] = new \AppBundle\Service\SignatureService();
