<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container9op5s4y\appTestDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container9op5s4y/appTestDebugProjectContainer.php') {
    touch(__DIR__.'/Container9op5s4y.legacy');

    return;
}

if (!\class_exists(appTestDebugProjectContainer::class, false)) {
    \class_alias(\Container9op5s4y\appTestDebugProjectContainer::class, appTestDebugProjectContainer::class, false);
}

return new \Container9op5s4y\appTestDebugProjectContainer(array(
    'container.build_hash' => '9op5s4y',
    'container.build_id' => '36e1a1df',
    'container.build_time' => 1528707546,
), __DIR__.\DIRECTORY_SEPARATOR.'Container9op5s4y');
